# -*- coding: utf-8 -*-
"""ChatbotProject_1_TopicSelection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ixVQzt71niUSdIUK08KuKokK5QgCizVa
"""

import pandas as pd
import numpy as np

def read_dataset(filename, user_input):
  QAdata = pd.read_csv(filename, encoding='latin1')
  topics = pd.DataFrame(QAdata['ArticleTitle'])
  topics = topics['ArticleTitle'].unique()
  print("You have selected the topic: ", topics[user_input])
  dataset = pd.DataFrame(QAdata[QAdata['ArticleTitle']==topics[user_input]])
  dataset = dataset.reset_index()
  
  return dataset